### ISSUE TITLE
use lds specification

### ISSUE THREAD

**Issue by travula** [vlead/vlabs-platform#11]
use this [lds spec](https://github.com/vlead/lab-specifications/blob/master/lds-specs/iiit-hyderabad/computer-programming-lab-labspec/e99791.json) to generate the github repo in the translators.

**Comment by sounak98** [comment]
This [repo](https://github.com/test-platform-to-to-deleted/expression-evaluation-e99791) has been created using translators `create_experiment` API with the [lds spec](https://github.com/vlead/lab-specifications/blob/master/lds-specs/iiit-hyderabad/computer-programming-lab-labspec/e99791.json).

**Comment by travula** [comment]
Because `content-type` is not present in these specifications, let us design this api the following way
1. Check for `content-type` in the specfication
2. Check for `content-type` in the api param
3. otherwise, set default to `org`
